
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/home/varun/.gemini/antigravity-cli/bin/"
      - "/home/varun/.local/bin/"
      - "/usr/lib/jvm/java-21-openjdk/bin/"
      - "/home/varun/Android/sdk/cmdline-tools/latest/bin/"
      - "/home/varun/Android/sdk/platform-tools/"
      - "/home/varun/Android/sdk/build-tools/35.0.0/"
      - "/home/varun/.npm-global/bin/"
      - "/home/varun/.cargo/bin/"
      - "/usr/local/bin/"
      - "/usr/bin/"
      - "/home/varun/go/bin/"
      - "/bin/"
    searched_directories:
      - "/home/varun/.gemini/antigravity-cli/bin/uname"
      - "/home/varun/.local/bin/uname"
      - "/usr/lib/jvm/java-21-openjdk/bin/uname"
      - "/home/varun/Android/sdk/cmdline-tools/latest/bin/uname"
      - "/home/varun/Android/sdk/platform-tools/uname"
      - "/home/varun/Android/sdk/build-tools/35.0.0/uname"
      - "/home/varun/.npm-global/bin/uname"
      - "/home/varun/.cargo/bin/uname"
      - "/usr/local/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/home/varun/.gemini/antigravity-cli/bin"
        - "/home/varun/.local/bin"
        - "/home/varun/.local/bin"
        - "/usr/lib/jvm/java-21-openjdk/bin"
        - "/home/varun/Android/sdk/cmdline-tools/latest/bin"
        - "/home/varun/Android/sdk/platform-tools"
        - "/home/varun/Android/sdk/build-tools/35.0.0"
        - "/home/varun/.npm-global/bin"
        - "/home/varun/.cargo/bin"
        - "/usr/local/bin"
        - "/usr/bin"
        - "/home/varun/go/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:218 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 7.1.9-arch1-2 - x86_64
...
